### ISSUE TITLE
mpvue小程序集成友盟，控制台提示集成成功，友盟后台数据统计不上

### ISSUE THREAD

**Issue by moveStar** [umeng/mp-demos#10]
**控制台提示：**
[UMENG] -- um_cache_5ecc727cdbc2ec0816fa16a4: getStorage:fail data not found

[UMENG] -- cache初始化成功:  {}
[UMENG] -- Lib对象初始化成功
[UMENG] -- 安装Lib接口成功
[UMENG] -- SDK集成成功
[UMENG] -- um_userid: getStorage:fail data not found
[UMENG] -- um_provider: getStorage:fail data not found
[UMENG] -- um_uuid: getStorage:fail data not found

**main.js文件配置如下：**
![20200528174200](https://user-images.githubusercontent.com/22618693/83126106-f592b980-a10a-11ea-945d-9e328fd1f944.png)

后台统计无数据，是什么原因呢？麻烦看一下

**Comment by pdap** [comment]
你这样两点
第一，初始化参数和调用init方法要在最前面
第二， 你初始化的参数 useOpenid 写了false，autoGetOpenid是true,如果是用auto的话，需要两个都开启true，并且到到官网去填写appid 和secret

**Comment by moveStar** [comment]
> 你这样两点
> 第一，初始化参数和调用init方法要在最前面
> 第二， 你初始化的参数 useOpenid 写了false，autoGetOpenid是true,如果是用auto的话，需要两个都开启true，并且到到官网去填写appid 和secret



你好，将useOpenid开启了：
![image](https://user-images.githubusercontent.com/22618693/83601769-d16c2800-a5a3-11ea-887a-9d135cebb544.png)
友盟配置：
![image](https://user-images.githubusercontent.com/22618693/83601718-b00b3c00-a5a3-11ea-8cf7-81e81ab98de3.png)

控制台提示没有变化，后台数据未统计上，是还需要在其他地方配置什么吗

**Comment by moveStar** [comment]
> 你这样两点
> 第一，初始化参数和调用init方法要在最前面
> 第二， 你初始化的参数 useOpenid 写了false，autoGetOpenid是true,如果是用auto的话，需要两个都开启true，并且到到官网去填写appid 和secret

谢谢，找到问题了，引入依赖的时候必须要放在最前面，否则只会显示SDK集成成功，出现数据发送成功才集成ok。
![image](https://user-images.githubusercontent.com/22618693/83832431-3ea2c900-a71c-11ea-94f6-194c499b4628.png)
![image](https://user-images.githubusercontent.com/22618693/83832506-6f82fe00-a71c-11ea-81e9-cf868c92d7c9.png)
