### ISSUE TITLE
uniapp开发微信小程序集成友盟统计，控制台提示getStorage:fail data not found

### ISSUE THREAD

**Issue by heyzqt** [umeng/mp-demos#15]
每次小程序在初始化的时候，控制台会显示友盟SDK集成成功和数据发送成功的提醒，同时也会有getStorage:fail data not found的警告⚠️，之后就再也不会出现，在友盟后台看统计数据也正常。

请问这里的getStorage:fail data not found会对统计数据有影响吗？

友盟微信小程序sdk版本：umtrack-wx@2.3.3

**控制台提示：**
[UMENG] -- cache初始化成功:  {}
[UMENG] -- Lib对象初始化成功
[UMENG] -- setOpenId: xxxxxxxxxx
[UMENG] -- showOptions:  xxxxxxx
[UMENG] -- session options: xxxxx
[UMENG] -- 开始新的session xxxxxxx
[UMENG] -- setSessionId:  xxxxxxx
[UMENG] -- 安装Lib接口成功
[UMENG] -- SDK集成成功
[UMENG] -- um_userid: getStorage:fail data not found
[UMENG] -- um_provider: getStorage:fail data not found
[UMENG] -- um_unid: getStorage:fail data not found

[UMENG] -- 数据发送成功: xxxxxx

看到这个issues说的类似的问题
[mpvue小程序集成友盟，控制台提示集成成功，友盟后台数据统计不上 #10](https://github.com/umeng/mp-demos/issues/10)

已经做到了
- 初始化参数和调用init方法在最前面
<img width="244" alt="截屏2020-08-18 下午3 38 48" src="https://user-images.githubusercontent.com/17877784/90484693-1e09dd00-e169-11ea-90e3-3289fe67a7e5.png">
<img width="310" alt="截屏2020-08-18 下午3 38 53" src="https://user-images.githubusercontent.com/17877784/90484700-2235fa80-e169-11ea-827c-49c1f16fe03f.png">

- umeng设置如下

```
uma.init({
  appKey: appKey,
  useOpenid: true,
  autoGetOpenid: false,
  debug: isDebug
});
```

**Comment by pdap** [comment]
没影响，是正常的
