### ISSUE TITLE
请问IOS14下如何不使用系统剪贴板

### ISSUE THREAD

**Issue by melunar** [umeng/mp-demos#19]
原生api 配置项 enableVerify ：false 可以支持关闭剪切板
目前taro不能支持
代码如下
` uma.init({
    appKey: '5edf156d978eea085d11e13f',
    useOpenid: true,
    autoGetOpenid: true,
    debug: !true,
    enableVerify: false
  })`
版本：
"umtrack-wx": "^2.3.5"

**Comment by pdap** [comment]
确保升级到最新版sdk，当前2.5.2，已彻底去除剪切板
