### ISSUE TITLE
友盟小程序的sdk使用后，小程序的onShareAppMessage功能是不是取不到that.data里面的值

### ISSUE THREAD

**Issue by woshiBloodhawk** [umeng/mp-demos#2]
友盟小程序的sdk使用后，小程序的onShareAppMessage功能是不是取不到that.data里面的值

**Comment by gzgogo** [comment]
新版本已经修复了这个问题，目前正在灰度发布阶段，可以通过下面步骤升级sdk：
微信
1. 删除本地的node_modules/umtrack-wx目录
2. 删除本地的miniprogram_npm目录
3. 安装最新版本：npm i umtrack-wx@nex
4. 确认最新版本为 2.2.1-0
5. 重新构建：微信开发者工具-工具-构建npm

支付宝
1. 删除本地的node_modules/umtrack-alipay目录
2. 安装最新版本：npm i umtrack-alipay@next
3. 确认最新版本为 2.2.1-0
4. 清空缓存，重新编译
