### ISSUE TITLE
MPX 小程序，友盟统计不能发送数据

### ISSUE THREAD

**Issue by xugongyang** [umeng/mp-demos#20]
用滴滴开源框架 MPX 开发的小程序，使用友盟小程序统计，数据不会没有发送。
无论是通过AppId 和 secret 自动获取 openid 还是代码 方式 wx.uma.setOpenid(openid) 都没有发送数据（日志没有数据发送）
wepy 我测试了，没有问题，是正常的。

请大佬们支持一下 MPX , 方便的话提供一个案例。

**Comment by GuanJdoJ** [comment]
需要适配使用构造器创建APP：
createApp(options, {customCtor: App})

**Comment by pdap** [comment]
已给出解
https://github.com/umeng/mp-demos/tree/master/mpx
