### ISSUE TITLE
uni-app 页面跳转发现没有上报请求

### ISSUE THREAD

**Issue by wil-x** [umeng/mp-demos#26]
# SDK 版本
`umtrack-wx` 版本 `2.5.2`

# 问题描述
`uni-app` 项目中，页面跳转发现未上报请求，无上报意味着无统计，不知是否正常？

# 问题重现步骤
1. 修改 `uni-app` 示例项目下 `uma.js` 的 `appKey` 为自己的 `appKey`
2. 新增一个全新的页面，并在 `/pages/index/index` 中新增点击按钮跳转新页面逻辑

![image](https://user-images.githubusercontent.com/42132616/109935160-3f4aa900-7d08-11eb-8461-986b6d6be564.png)

![image](https://user-images.githubusercontent.com/42132616/109935184-47a2e400-7d08-11eb-96a7-abb1436dd746.png)

**Comment by pdap** [comment]
参考 [小程序数据发送时机图](https://developer.umeng.com/docs/147615/detail/171071?spm=a311a.7996332.0.0.42c03080Vf58LP) 页面切换时，只采集不上报，退出时上报
