### ISSUE TITLE
uniapp集成友盟编译到微信小程序不能自定义分享

### ISSUE THREAD

**Issue by HYG1904** [umeng/mp-demos#31]
在main.js中引入友盟不进行初始化，会导致小程序不能自定义分享。

**Comment by pdap** [comment]
@HYG1904 麻烦提供下uni-app版本，还有编译的目标平台

> 在main.js中引入友盟不进行初始化，会导致小程序不能自定义分享。

**Comment by pdap** [comment]
@HYG1904 已经修复发beta版了，预计这周发正式
可以安装这个版本 npm i umtrack-wx@2.6.3-beta.16033188
或者npm view umtrack-wx@beta  查看最新的beta包下载地址
